// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CourseData.Models;

public partial class Courseschedule
{
    public Guid Id { get; set; }

    public Guid Courseid { get; set; }

    public Guid Teacherid { get; set; }

    public DateOnly Sdate { get; set; }

    public DateOnly Edate { get; set; }

    public string Location { get; set; }

    public virtual Course Course { get; set; }

    public virtual Teacher Teacher { get; set; }
}