// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CourseData.Models;

public partial class Course
{
    public Guid Id { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public int Times { get; set; }

    /// <summary>
    /// 填課程說明
    /// </summary>
    public string Description { get; set; }

    public virtual ICollection<Courseschedule> Courseschedules { get; set; } = new List<Courseschedule>();
}